version: '3.9'

services:
  mysql:
    container_name: mysql
    image: docker.io/library/mariadb:10.9
    environment:
      MARIADB_ROOT_PASSWORD: ${TMP_MYSQL_ROOT_PASSWORD}
  
  mysql-restore-dev:
    container_name: mysql-restore-dev
    build:
      context: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      TARGET_MYSQL_HOST: ${TARGET_MYSQL_HOST}
      TARGET_MYSQL_USER: ${TARGET_MYSQL_USER}
      TARGET_MYSQL_PASSWORD: ${TARGET_MYSQL_PASSWORD}
      TMP_MYSQL_ROOT_PASSWORD: ${TMP_MYSQL_ROOT_PASSWORD}
      RCLONE_CONFIG_BACKUP_ENDPOINT: ${RCLONE_CONFIG_BACKUP_ENDPOINT}
      RCLONE_CONFIG_BACKUP_ACCESS_KEY_ID: ${RCLONE_CONFIG_BACKUP_ACCESS_KEY_ID}
      RCLONE_CONFIG_BACKUP_SECRET_ACCESS_KEY: ${RCLONE_CONFIG_BACKUP_SECRET_ACCESS_KEY}