FROM docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2

RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-smartcn
RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install https://get.infini.cloud/elasticsearch/analysis-stconvert/7.10.2
