name: Build Docker image and publish to GitHub Container Registry

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and push 52w-elasticsearch
      uses: docker/build-push-action@v6
      with:
        context: ./52w-elasticsearch
        file: ./52w-elasticsearch/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/52w-elasticsearch:latest
    - name: Build and push poolcounter
      uses: docker/build-push-action@v6
      with:
        context: ./poolcounter
        file: ./poolcounter/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/poolcounter:latest
    - name: Build and push 52w-nginx
      uses: docker/build-push-action@v6
      with:
        context: ./52w-nginx
        file: ./52w-nginx/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/52w-nginx:latest